apiVersion: v1
kind: Service
metadata:
  name: nacos-rest-provider 
  namespace: mesh
  labels:
    app: nacos-rest-provider
spec:
  type: NodePort
  ports:
  - port: 8004
    nodePort: 31001
    name: request
  - port: 5009
    nodePort: 31002
    name: debug
  selector:
    app: nacos-rest-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-rest-provider
  namespace: mesh
  labels:
    app: nacos-rest-provider 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-rest-provider 
  template:
    metadata:
      labels:
        app: nacos-rest-provider
        sermant-injection: enabled 
    spec:
      containers:
      - name: nacos-rest-provider
        image: provider:1.0.2
        ports:
        - containerPort: 5009 
        - containerPort: 8004 
        env:
        # 注册中心地址
        - name: "dynamic.config.serverAddress"
          value: "127.0.0.1:30110"
        - name: "dynamic.config.dynamicConfigType"
          value: "KIE"
        # KIE配置中心地址
        - name: "servicecomb.service.address"
          value: "http://127.0.0.1:30100"
        - name: "servicecomb.service.enableSpringRegister"
          value: "true"
        - name: "servicecomb.service.openMigration"
          value: "false"
        - name: "grace.rule.enableSpring"
          value: "true"
        # 配置注册延迟时间, 单位秒
        - name: "grace.rule.startDelayTime"
          value: "10"
      imagePullSecrets:
        - name: default-secret
