apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-router-gray-provider
  labels:
    app: spring-cloud-router-gray-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-router-gray-provider
  template:
    metadata:
      labels:
        app: spring-cloud-router-gray-provider
        sermant-injection: enabled
    spec:
      containers:
        - name: spring-cloud-router-gray-provider
          image: spring-cloud-router-provider:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: "SERVICE_META_VERSION"
              value: "1.0.1"
            - name: "SERVICE_META_PARAMETERS"
              value: "group:gray"
      imagePullSecrets:
        - name: default-secret