apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-router-provider
  labels:
    app: spring-cloud-router-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-router-provider
  template:
    metadata:
      labels:
        app: spring-cloud-router-provider
        sermant-injection: enabled
    spec:
      containers:
        - name: spring-cloud-router-provider
          image: spring-cloud-router-provider:1.0.0
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: default-secret