apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
        sermant-injection: enabled
    spec:
      containers:
        - name: consumer
          image: consumer:1.0.0
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: default-secret