apiVersion: v1
kind: Service
metadata:
  name: nacos-rest-data 
  namespace: mesh
  labels:
    app: nacos-rest-data
spec:
  type: NodePort
  ports:
  - port: 8008
    nodePort: 31011
    name: request
  - port: 5008
    nodePort: 31012
    name: debug
  selector:
    app: nacos-rest-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-rest-data
  namespace: mesh
  labels:
    app: nacos-rest-data 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-rest-data 
  template:
    metadata:
      labels:
        app: nacos-rest-data
        sermant-injection: enabled 
    spec:
      containers:
      - name: nacos-rest-data
        image: data:1.0.2
        ports:
        - containerPort: 5008 
        - containerPort: 8008 
        env:
        # 注册中心地址
        - name: "dynamic.config.serverAddress"
          value: "127.0.0.1:30110"
        - name: "dynamic.config.dynamicConfigType"
          value: "KIE"
        # KIE配置中心地址
        - name: "servicecomb.service.address"
          value: "http://127.0.0.1:30100"
        - name: "servicecomb.service.enableSpringRegister"
          value: "true"
        - name: "servicecomb.service.openMigration"
          value: "false"
      imagePullSecrets:
        - name: default-secret
