apiVersion: v1
kind: Service
metadata:
  name: nacos-rest-provider-close-grace 
  namespace: mesh
  labels:
    app: nacos-rest-provider-close-grace
spec:
  type: NodePort
  ports:
  - port: 8004
    nodePort: 31003
    name: request
  - port: 5009
    nodePort: 31004
    name: debug
  selector:
    app: nacos-rest-provider-close-grace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-rest-provider-close-grace
  namespace: mesh
  labels:
    app: nacos-rest-provider-close-grace 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nacos-rest-provider-close-grace 
  template:
    metadata:
      labels:
        app: nacos-rest-provider-close-grace
        sermant-injection: enabled 
    spec:
      containers:
      - name: nacos-rest-provider-close-grace
        image: provider:1.0.2
        ports:
        - containerPort: 5009 
        - containerPort: 8004 
        env:
        - name: "spring.application.name"
          value: "nacos-rest-provider-close-grace"
        # 注册中心地址
        - name: "dynamic.config.serverAddress"
          value: "127.0.0.1:30110"
        - name: "dynamic.config.dynamicConfigType"
          value: "KIE"
        # KIE配置中心地址
        - name: "servicecomb.service.address"
          value: "http://127.0.0.1:30100"
        - name: "servicecomb.service.enableSpringRegister"
          value: "true"
        - name: "servicecomb.service.openMigration"
          value: "false"
        # 关闭优雅下线功能
        - name: "grace.rule.enableSpring"
          value: "false"
        - name: "grace.rule.enableGraceShutdown"
          value: "false"
        - name: "grace.rule.enableOfflineNotify"
          value: "false"
        - name: "grace.rule.enableHealthCheck"
          value: "false"
      imagePullSecrets:
        - name: default-secret
