spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lowerCaseServiceIdd: true
      default-filters:
        - StripPrefix=1

server:
  port: 28030
dubbo:
  application:
    name: gateway
  protocol:
    name: dubbo
    port: 28830
  registry:
    address: sc://127.0.0.1:30100