spring:
  application:
    name: spring-cloud-registry-consumer

server:
  port: 8161

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000