spring:
  application:
    name: spring-cloud-registry-consumer
  cloud:
    zookeeper:
      connect-string: localhost:2181

server:
  port: 8161

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000