apiVersion: v1
kind: Service
metadata:
  name: spring-consumer
  labels:
    app: spring-consumer
spec:
  type: NodePort
  ports:
    - port: 8005
      nodePort: 31001
      name: request
  selector:
    app: spring-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-consumer
  labels:
    app: spring-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-consumer
  template:
    metadata:
      labels:
        app: spring-consumer
        sermant-injection: enabled
    spec:
      containers:
        - name: spring-consumer
          image: spring-consumer:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8005
          # 若遇到域名无法解析问题，请将下面的配置开启
          # env:
          # - name: "servicecomb_service_preferIpAddress"
          #   value: "true"
      imagePullSecrets:
        - name: default-secret
